import type { Client as McpClient } from "@modelcontextprotocol/sdk/client/index.js";
import { callToolLogged } from "../mcp-tools.js";
import { sortChanges } from "./dependency-sort.js";
import type { ApplyEvent, Change, DomainData, EdgeAppData, EdgeFunctionData, RuleData } from "./types.js";

/**
 * Maps an MCP tool result to its `data.id` so a created resource can be
 * referenced by subsequent changes (e.g. domain → app just created).
 */
function extractCreatedId(result: unknown): number | undefined {
  const r = result as { content?: Array<{ type: string; text?: string }> };
  const text = r.content?.find((c) => c.type === "text")?.text;
  if (!text) return undefined;
  try {
    const parsed = JSON.parse(text) as { id?: number; data?: { id?: number }; results?: { id?: number } };
    return parsed.id ?? parsed.data?.id ?? parsed.results?.id;
  } catch {
    return undefined;
  }
}

/**
 * Local placeholder ids generated by the frontend (e.g. "new-abc12") are
 * remapped to real numeric ids returned by the API as `create` ops succeed.
 * Subsequent changes that reference the placeholder get patched in-place.
 */
function rewriteReferences(remaining: Change[], localId: string, realId: number) {
  for (const c of remaining) {
    if (c.op === "create" && c.kind === "domain") {
      const d = c.data as DomainData;
      if (d.edge_application_id === localId) d.edge_application_id = realId;
    }
    if (c.op === "create" && c.kind === "rule") {
      const r = c.data as RuleData;
      if (r.application_id === localId) r.application_id = realId;
    }
  }
}

async function runChange(mcp: McpClient, change: Change): Promise<number | undefined> {
  switch (change.op) {
    case "create": {
      if (change.kind === "edge_app") {
        const d = change.data as EdgeAppData;
        const res = await callToolLogged(mcp, "azion_create_application", {
          name: d.name,
          delivery_protocol: d.delivery_protocol ?? "http,https",
        });
        return extractCreatedId(res);
      }
      if (change.kind === "edge_function") {
        const d = change.data as EdgeFunctionData;
        const res = await callToolLogged(mcp, "azion_create_function", {
          name: d.name,
          code: d.code,
          language: d.language ?? "javascript",
          initiator_type: d.initiator_type,
        });
        return extractCreatedId(res);
      }
      if (change.kind === "domain") {
        const d = change.data as DomainData;
        const res = await callToolLogged(mcp, "azion_create_domain", {
          name: d.name,
          edge_application_id: d.edge_application_id,
          cnames: d.cnames,
          cname_access_only: d.cname_access_only,
        });
        return extractCreatedId(res);
      }
      if (change.kind === "rule") {
        const d = change.data as RuleData;
        const res = await callToolLogged(mcp, "azion_create_rule", {
          application_id: d.application_id,
          phase: d.phase,
          name: d.name,
          description: d.description,
          criteria: d.criteria ?? [[{ variable: "${uri}", operator: "starts_with", input_value: "/" }]],
          behaviors: d.behaviors ?? [{ name: "deliver" }],
        });
        return extractCreatedId(res);
      }
      return undefined;
    }
    case "update": {
      if (change.kind === "edge_app") {
        const d = change.after as EdgeAppData;
        await callToolLogged(mcp, "azion_update_application", {
          application_id: change.id,
          name: d.name,
          delivery_protocol: d.delivery_protocol,
        });
      } else if (change.kind === "edge_function") {
        const d = change.after as EdgeFunctionData;
        await callToolLogged(mcp, "azion_update_function", {
          function_id: change.id,
          name: d.name,
          code: d.code,
        });
      } else if (change.kind === "domain") {
        const d = change.after as DomainData;
        await callToolLogged(mcp, "azion_update_domain", {
          domain_id: change.id,
          name: d.name,
          cnames: d.cnames,
        });
      } else if (change.kind === "rule") {
        const d = change.after as RuleData;
        await callToolLogged(mcp, "azion_update_rule", {
          application_id: d.application_id,
          phase: d.phase,
          rule_id: change.id,
          name: d.name,
        });
      }
      return undefined;
    }
    case "delete": {
      if (change.kind === "edge_function") {
        await callToolLogged(mcp, "azion_delete_function", { function_id: change.id });
      } else if (change.kind === "domain") {
        await callToolLogged(mcp, "azion_delete_domain", { domain_id: change.id });
      } else if (change.kind === "rule") {
        const before = change.before as RuleData;
        await callToolLogged(mcp, "azion_delete_rule", {
          application_id: before.application_id,
          phase: before.phase,
          rule_id: change.id,
        });
      }
      // edge_app delete isn't exposed by the MCP today; skipped silently here
      // and reported as a no-op in v1.
      return undefined;
    }
  }
}

export async function applyChangeset(
  mcp: McpClient,
  changes: Change[],
  emit: (ev: ApplyEvent) => void,
): Promise<void> {
  const sorted = sortChanges(changes);
  const total = sorted.length;

  for (let i = 0; i < sorted.length; i++) {
    const change = sorted[i];
    emit({ type: "progress", index: i, total, change, status: "running" });
    try {
      const createdId = await runChange(mcp, change);
      if (change.op === "create" && createdId != null) {
        rewriteReferences(sorted.slice(i + 1), change.localId, createdId);
      }
      emit({ type: "result", index: i, change, status: "ok", createdId });
    } catch (err) {
      const message = (err as Error).message ?? "unknown error";
      emit({ type: "result", index: i, change, status: "error", message });
      emit({ type: "error", message: `Apply halted at step ${i + 1}/${total}: ${message}` });
      return;
    }
  }
  emit({ type: "done" });
}
